# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aca906f1514b8b0e7085bd0af1cbd003ebc8759c4631508d462391ecf6549fb5b010e679cfa7e1476dde833ea861c9a1131ec06bc4ea7d29c7b117ccec8b123a

test:
  secret_key_base: dd561470733b5baade5b88671aef3964337bbff3cf551fd29b03b729c5bc155d85fc109b8d8d9c3c2898b1f315a3c2e2e06dfd25c50f452467d1799f02769403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
